
- name: Get Islandora bagger Microservice from Github
  git:
    repo: https://github.com/roblib/islandora_bagger.git
    dest: "{{ bagger_home }}/islandora_bagger"
    force: yes

- name: set PHP memory limit
  become: yes
  ini_file:
    path: /etc/php/7.2/cli/php.ini
    section: PHP
    option: memory_limit
    value: '-1'

- name: Update repositories cache and install "intl" package
  apt:
    name: php7.2-intl
    update_cache: yes

- name: Install Baggit tools
  composer:
    command: require
    arguments: whikloj/bagittools
    working_dir: "{{ bagger_home }}/islandora_bagger"

- name: Change bagger directory ownership, group and permissions
  file:
    path: "{{ bagger_home }}/islandora_bagger"
    owner:  "{{ ansible_ssh_user }}"
    group:  "{{ ansible_ssh_user }}"
    mode: '0755'
    recurse: True

- name: "Install  {{ bagger_home }}/islandora_bagger"
  shell: composer install
  args:
    chdir: "{{ bagger_home }}/islandora_bagger"

- name: Add Islandora Ansible Routes
  blockinfile:
    path: "{{ bagger_home }}/islandora_bagger/config/routes.yaml"
    create: no
    block: |
      app_islandora_bagger_create_bag_added:
          path: /
          controller: App\Controller\IslandoraBaggerController::create
          methods: [POST]
      app_islandora_bagger_get_bag_location_added:
          path: /
          controller: App\Controller\IslandoraBaggerController::getLocation
          methods: [GET, HEAD]

- name: Clear Symfony cache
  command: rm -rf /var/www/html/islandora_bagger/var/cache/dev


- name: Open permissions for logging
  file:
    path: "{{ bagger_home }}/islandora_bagger/var/log"
    owner:  "{{ ansible_ssh_user }}"
    group:  "{{ ansible_ssh_user }}"
    mode: '0777'
    recurse: True

- name: Open cache
  file:
    path: "{{ bagger_home }}/islandora_bagger/var/cache/dev"
    owner:  "{{ ansible_ssh_user }}"
    group:  "{{ ansible_ssh_user }}"
    mode: '0777'
    recurse: True

- name: Create target directory
  file:
    path: "{{ private_file_dir }}/bagger_config"
    state: directory
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    mode: '0777'
  become: yes

- name: Install Bagger RDM config file
  template:
    src: "bagger_config.j2"
    dest: "{{ private_file_dir }}/bagger_config/islandora_bagger_config.yml"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
  become_user: root

- name: reset PHP memory limit
  become: yes
  ini_file:
    path: /etc/php/7.2/cli/php.ini
    section: PHP
    option: memory_limit
    value: '128M'


- name: restart apache
  service:
    name: apache2
    state: restarted

- name: Install Drupal Islandora bagger module from Github
  git:
    repo: https://github.com/roblib/islandora_bagger_integration.git
    dest: "{{ drupal_core_path }}/modules/contrib/islandora_bagger_integration"
    force: yes

- name: Enable bagger drupal module
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y en islandora_bagger_integration"

- name: Set Bagger Mode
  command: "{{ drush_path }} --root {{ drupal_core_path }} cset islandora_bagger_integration.settings islandora_bagger_mode {{ islandora_bagger_mode }} -y"

- name: Set Bagger Config Path
  command: "{{ drush_path }} --root {{ drupal_core_path }} cset islandora_bagger_integration.settings islandora_bagger_default_config_file_path {{ islandora_bagger_default_config_file_path }} -y"

- name: Set Bagger Local Install Path
  command: "{{ drush_path }} --root {{ drupal_core_path }} cset islandora_bagger_integration.settings islandora_bagger_local_bagger_directory {{ islandora_bagger_local_bagger_directory }} -y"
